# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0919c218c0a0a4b85b36250b6d24a41c9ef7b7a2d38fb9caea6a0d4278aa744e9f891150d82b45e48ca24a0307a493bd41a8eeea1a714a2bcea8dba6d247dc97

test:
  secret_key_base: 71f02929c6e9d8906f5247ab4e0cbf4137aca3f1bca351c9e74209e7469a16a333e6e61639c053d6795ac8136f89115295127ee85076d12ff2c04895ea48fa82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
